/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/add-alarm`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/alarm` | `/alarm`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/clock` | `/clock`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stopwatch` | `/stopwatch`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/timer` | `/timer`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/add-alarm`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/alarm` | `/alarm`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/clock` | `/clock`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/stopwatch` | `/stopwatch`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/timer` | `/timer`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/add-alarm${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/alarm${`?${string}` | `#${string}` | ''}` | `/alarm${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/clock${`?${string}` | `#${string}` | ''}` | `/clock${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/stopwatch${`?${string}` | `#${string}` | ''}` | `/stopwatch${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/timer${`?${string}` | `#${string}` | ''}` | `/timer${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/add-alarm`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/alarm` | `/alarm`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/clock` | `/clock`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stopwatch` | `/stopwatch`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/timer` | `/timer`; params?: Router.UnknownInputParams; };
    }
  }
}
